image: node:fermium-alpine
pipelines:
  # default:
  #   - step: &build-test
  #       name: Build & Test
  #       caches:
  #         - node
  #       script:
  #         - apk add firefox-esr
  #         - yarn install
  #         - yarn lint
  #         - yarn test --configuration=ci
  #           # - yarn e2e --configuration=ci
  #         - yarn build --configuration=ci
  # pull-requests:
  #   '**':
  #     - step: *build-test
  branches:
    release/v4:
      - step:
          image: cticti/apspace:08.20
          caches:
            - node
          script:
            - npm i
            - ionic build --prod
            - aws s3 sync www/ s3://apspace-staging/ --acl public-read
