image: node:erbium-alpine
pipelines:
  # default:
  #   - step: &build-test
  #       name: Build & Test
  #       caches:
  #         - node
  #       script:
  #         - apk add firefox-esr
  #         - yarn install
  #         - yarn lint
  #         - yarn test --configuration=ci
  #           # - yarn e2e --configuration=ci
  #         - yarn build --configuration=ci
  # pull-requests:
  #   '**':
  #     - step: *build-test
  branches:
    production:
    - step:
        image: cticti/apspace:08.20
        caches:
          - node
        script:
          - git config --global user.name $GIT_USERNAME
          - git config --global user.email cti@apiit.edu.my
          - git config --global user.password $GIT_PASSWORD
          - git config --global credential.helper cache
          - echo $GOOGLE > google-services.json
          - git remote add upstream https://$GIT_USERNAME:$GIT_PASSWORD@bitbucket.org/ctiteam/apspace-build.git
          - git add google-services.json
          - git commit -m "chore:add google json file"
          - git push upstream production
          - npm i
          - ionic build --prod
          - aws s3 sync www/ s3://apspace-production/ --acl public-read
          - aws cloudfront create-invalidation --distribution-id E2U0MAK0TADMRA --paths "/*"

    staging:
    - step:
        image: cticti/apspace:08.20
        caches:
          - node
        script:
          - npm i
          - ionic build --prod
          - aws s3 sync www/ s3://apspace-staging/ --acl public-read
